# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.runs/bd_0_hls_inst_0_synth_1/.Xil/Vivado-25676-Zenbook_Tomtom/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter sdxStrategy 3
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog {
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_a.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_CONTROL_BUS_s_axi.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_fadd_32bkb.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_fmul_32cud.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_mac_muldEe.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_mac_muleOg.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel_out.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/verilog/HLS_accel.v
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/synth/bd_0_hls_inst_0.v
    }
      rt::read_vhdl -lib xbip_utils_v3_0_9 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_5 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_5 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_5 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_5 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_5 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_14 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_7 c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/c63e/hdl/floating_point_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/ip/HLS_accel_ap_fadd_3_no_dsp_32.vhd
      c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ipshared/2d24/hdl/ip/HLS_accel_ap_fmul_2_no_dsp_32.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.runs/bd_0_hls_inst_0_synth_1/.Xil/Vivado-25676-Zenbook_Tomtom/realtime/bd_0_hls_inst_0_synth.xdc
    rt::sdcChecksum
    set rt::top bd_0_hls_inst_0
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.runs/bd_0_hls_inst_0_synth_1/.Xil/Vivado-25676-Zenbook_Tomtom/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
