# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/HLS_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thoms/Universite/H2024/INF3610/INF3610-TPs/TP2/hls_architecture2/implementation_sol_2_2/hls_wrapped_mmult_prj/solution2_2/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/HLS_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
